name: Hale compiler (c-bot) 
on: [push]
jobs:
  build-project:
    name: Compile theme files 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: NPM install
        run: npm install
      - name: NPM build 
        run: npm run build
      - name: Upload compiled site
        uses: actions/upload-artifact@v3
        with:
          name: hale-theme-prod 
          path: | 
            .
            !./node_modules
            !.git
            !.sql
            !.env
          if-no-files-found: error
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-project
    permissions:
      contents: write
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Download site content
        uses: actions/download-artifact@v3
        with:
          name: hale-theme-prod
      - name: Archive site
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'hale.zip'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          id: create_release
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
